---
- hosts: rabbitmq
  sudo: true
  vars:
  rabbitmq_version: 3.6.1
  remote_user: YOUR_USER


 tasks:
  - name: add EPEL repository
    command: "{{ item }}"
    with_items:
  - wget http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
  - rpm -Uvh epel-release-6*.rpm
#    - wget http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
#    - rpm -Uvh epel-release-7*.rpm


  - name: install Erlang for rabbitmq-server
    yum: name=erlang state=present

  - name: ensure python-software-properties is installed
    yum: pkg=python-software-properties state=installed

  - name: download the rabbitmq-server
    command: "{{ item }}"
    with_items:
       - wget https://www.rabbitmq.com/releases/rabbitmq-server/v3.6.1/rabbitmq-server-generic-unix-3.6.1.tar.xz
       - tar -xvf rabbitmq-server-generic-unix-3.6.1.tar.xz -C /opt/
       - sh /opt/rabbitmq_server-3.6.1/sbin/rabbitmq-server


  - name: enable rabbitmq plugins
    rabbitmq_plugin: names=rabbitmq_management,rabbitmq_tracing,rabbitmq_federation state=enabled
    notify:
    - restart rabbitmq

  - name: add users
    rabbitmq_user: user={{item}} password=password tags=administrator,{{item}} vhost=/ configure_priv=.* write_priv=.* read_priv=.* state=present
    with_items:
    - testuser1
    - testuser2

  - name: remove default guest user
    rabbitmq_user: user=guest state=absent

  - name: ensure vhost /test is present
    rabbitmq_vhost: name=/test state=present

  - name: set federation local-username
    rabbitmq_parameter: component=federation name=local-username value='"testuser1"' state=present

  handlers:
  - name: restart rabbitmq
    service: name=rabbitmq-server state=restarted
